/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author dan5-
 */
public class frmP2 extends javax.swing.JFrame {

    /**
     * Creates new form frmP2
     */
    public frmP2() {
        initComponents();
    }

    public JMenu getMnuAyuda() {
        return mnuAyuda;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public JMenuItem getMnuConCli() {
        return mnuConCli;
    }

    public void setMnuConCli(JMenuItem mnuConCli) {
        this.mnuConCli = mnuConCli;
    }

    public JMenuItem getMnuConHosp() {
        return mnuConHosp;
    }

    public void setMnuConHosp(JMenuItem mnuConHosp) {
        this.mnuConHosp = mnuConHosp;
    }

    public JMenuItem getMnuHabitaciones() {
        return mnuHabitaciones;
    }

    public void setMnuHabitaciones(JMenuItem mnuHabitaciones) {
        this.mnuHabitaciones = mnuHabitaciones;
    }

    public JMenuItem getMnuRegHos() {
        return mnuRegHos;
    }

    public void setMnuRegHos(JMenuItem mnuRegHos) {
        this.mnuRegHos = mnuRegHos;
    }
    

    public void setMnuAyuda(JMenu mnuAyuda) {
        this.mnuAyuda = mnuAyuda;
    }

    public JMenuItem getMnuRegCli() {
        return mnuRegCli;
    }

    public void setMnuRegCli(JMenuItem mnuRegCli) {
        this.mnuRegCli = mnuRegCli;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JDesktopPane getEscritorio() {
        return Escritorio;
    }

    public void setEscritorio(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        Escritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuRegCli = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuRegHos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        mnuCli = new javax.swing.JMenu();
        mnuConCli = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuConHosp = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuHabitaciones = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setRollover(true);

        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("0:0:0 ");
        lblHora.setMaximumSize(new java.awt.Dimension(45, 14));
        lblHora.setPreferredSize(new java.awt.Dimension(50, 14));
        lblHora.setRequestFocusEnabled(false);
        jToolBar1.add(lblHora);

        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("0/1/0");
        jToolBar1.add(lblFecha);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1233.jpg"))); // NOI18N

        Escritorio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscritorioLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Principal");

        mnuRegCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuRegCli.setText("Registro Cliente");
        mnuRegCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegCliActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRegCli);
        jMenu1.add(jSeparator2);

        mnuRegHos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuRegHos.setText("Registro Hospedaje");
        mnuRegHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegHosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRegHos);
        jMenu1.add(jSeparator3);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setText("Salir");
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        mnuCli.setForeground(new java.awt.Color(255, 255, 255));
        mnuCli.setText("Consulta");

        mnuConCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuConCli.setText("Clientes Registrados");
        mnuConCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConCliActionPerformed(evt);
            }
        });
        mnuCli.add(mnuConCli);
        mnuCli.add(jSeparator1);

        mnuConHosp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuConHosp.setText("Hospedajes");
        mnuCli.add(mnuConHosp);
        mnuCli.add(jSeparator6);

        mnuHabitaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuHabitaciones.setText("Habitaciones");
        mnuCli.add(mnuHabitaciones);

        jMenuBar1.add(mnuCli);

        mnuAyuda.setForeground(new java.awt.Color(255, 255, 255));
        mnuAyuda.setText("Otras opciones.....");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Ayuda");
        mnuAyuda.add(jMenuItem4);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("Hotel Descanso Feliz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuRegCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegCliActionPerformed

    private void mnuConCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuConCliActionPerformed

    private void mnuRegHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegHosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegHosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuCli;
    private javax.swing.JMenuItem mnuConCli;
    private javax.swing.JMenuItem mnuConHosp;
    private javax.swing.JMenuItem mnuHabitaciones;
    private javax.swing.JMenuItem mnuRegCli;
    private javax.swing.JMenuItem mnuRegHos;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
